language: node_js
node_js:
- '0.10'
script:
- npm test

env:
  global:
    secure: AVVJWU+38QcV5HmdkzYbyUyKsuXk4iBeuCE5ANRFltFtmulqLZDXHGeEv5VBhH22e67lYPNgFclaSZ0k6WT08aeZVeVKw8YgEay3YuHoWJvslfV8BbNN94i9Yk3fval9RAI4bZ5/kEbNLplLImKea7CZwHMuoIqYLySUbMLXLwI=

deploy:
  provider: npm
  email: i59naga@icloud.com
  api_key:
    secure: O/ogmeSYzThLwNbIsrnw0d+YRW5Z4+sEbaINSmZstA0CQ3P7LdvejajF/HvlgW4ccJX9v4VOqunlbBva/Dxg3qeHBQ1ma+LO7x8aRdNOwm1HWRcB72DKowniu32JOMzh2/txBrALYAStD92lm0xbrOUNCu5c9FFfkh3qnNbOkSU=
