# Quick boot options
sudo: false
cache:
  directories:
    - node_modules

# Language options
language: node_js
node_js:
  - '0.10'

# COVERALLS_REPO_TOKEN
env:
  global:
    secure: UbIpGPLxe+plgOOQJgpdjpYumBjBUq9pNwW7TNFnkTLhgaBBlCUMh3UfaHfAz+PA8GqKDQYMbahEgdk5LqP5lD5i9tMK0CModeAwtEuy8Mm4pwOQwPw2tWr+8FsI0/vqL6XOkhwNhJdiMNp17DZJHIlbk3AlFoF2iBiplrnRfOE=

# Npm publish options
before_deploy:
  - npm install coffee-script --global
deploy:
  provider: npm
  email: i59naga@icloud.com
  api_key:
    secure: O/ogmeSYzThLwNbIsrnw0d+YRW5Z4+sEbaINSmZstA0CQ3P7LdvejajF/HvlgW4ccJX9v4VOqunlbBva/Dxg3qeHBQ1ma+LO7x8aRdNOwm1HWRcB72DKowniu32JOMzh2/txBrALYAStD92lm0xbrOUNCu5c9FFfkh3qnNbOkSU=
