language: node_js
node_js:
- '0.10'
script:
- npm test
env:
  global:
    secure: AVVJWU+38QcV5HmdkzYbyUyKsuXk4iBeuCE5ANRFltFtmulqLZDXHGeEv5VBhH22e67lYPNgFclaSZ0k6WT08aeZVeVKw8YgEay3YuHoWJvslfV8BbNN94i9Yk3fval9RAI4bZ5/kEbNLplLImKea7CZwHMuoIqYLySUbMLXLwI=

deploy:
  provider: npm
  email: i59naga@icloud.com
  api_key:
    secure: YLkE2zPY6KrUY6WmOgbuz1ILj5USQb4JnZ/3FDugLo9rGsgfP6jRJDG4U4vCn89s8Y5THOsELWEciNhtzw1SsbRClLSg/fg1XOC2BgeYKhwj1kYTY8mfIfFZA0//h4/kZS+6/rgEFRQaVFBfq5FsTCNdUxQ5FKPNsaAerm/pTCw=
